# Generated by Django 5.2.1 on 2025-05-29 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailverification',
            old_name='is_user',
            new_name='is_used',
        ),
    ]
