# Generated by Django 5.2.1 on 2025-06-06 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_user_complaint_complainant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='p2p_followers',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='p2p_rating',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='status',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='account_status',
            field=models.CharField(choices=[('active', 'Активный'), ('inactive', 'Неактивный'), ('frozen', 'Заморожен'), ('banned', 'Забанен')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='balance',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='headers/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='secret_key',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('admin', 'Admin'), ('manager', 'Manager')], default='user', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='tag_nickname',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
